In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)
import numpy as np

print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
print(np.show_config())

NumPy version: 1.19.5

NumPy configuration:
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [3]:
#### 3. Create a null vector of size 10 (★☆☆)
import numpy as np

null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#### 4. How to find the memory size of any array (★☆☆)
import numpy as np

# Create a sample array
arr = np.zeros((4, 4))  

# Calculate memory size in bytes
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 128 bytes


In [5]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
import numpy as np; help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [6]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1  # Set the fifth value 
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)

# Print the vector
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

# Print the reversed vector
print(vector)
print(reversed_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.arange(9).reshape(3, 3)

# Print the matrix
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
# Create the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Find indices of non-zero elements
nonzero_indices = np.nonzero(arr)

# Print the indices
print(nonzero_indices)

(array([0, 1, 4], dtype=int64),)


In [11]:
#### 11. Create a 3x3 identity matrix (★☆☆)
identity_matrix = np.eye(3)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
random_array = np.random.rand(3, 3, 3)

# Print the random array
print(random_array)

[[[0.98576288 0.33794194 0.59827517]
  [0.74776425 0.33827317 0.51509568]
  [0.22904804 0.57696549 0.41345745]]

 [[0.95190554 0.20493203 0.18543524]
  [0.55687698 0.68094899 0.90677149]
  [0.50407559 0.81518906 0.18737974]]

 [[0.61094578 0.35272057 0.00317454]
  [0.02793458 0.92596273 0.7315043 ]
  [0.13160677 0.48782791 0.53165218]]]


In [13]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

# Create a 10x10 array with random values
random_array_10x10 = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_value = np.min(random_array_10x10)
max_value = np.max(random_array_10x10)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.006563056513481991
Maximum value: 0.9933367081453909


In [14]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

# Print the random vector and mean value
print("Random Vector:")
print(random_vector)
print("\nMean Value:", mean_value)

Random Vector:
[2.74007232e-01 1.56303575e-01 3.45033139e-01 3.57771280e-01
 9.42929791e-02 2.06086121e-01 2.64319752e-01 7.39188976e-01
 9.21969847e-01 1.30569525e-01 2.19606331e-01 3.86547555e-02
 3.43237207e-01 7.63053369e-04 6.68758001e-01 8.84462915e-01
 7.67564404e-01 4.32450237e-01 3.78215227e-02 9.54792286e-01
 7.77651394e-01 6.70021689e-01 5.31060463e-01 3.75431413e-02
 9.36200692e-01 5.26918537e-01 2.05257235e-01 1.07171193e-01
 6.19232060e-01 8.68394007e-01]

Mean Value: 0.43723678505414865


In [15]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
rows, cols = 5, 5  # You can adjust the dimensions as needed

# Create a 2D array with 1 on the border and 0 inside
array = np.ones((rows, cols))
array[1:-1, 1:-1] = 0

# Print the resulting array
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
existing_array = np.ones((3, 3))

# Specify the size of the border
border_size = 1  # You can adjust the border size as needed

# Create a new array with the border
new_array = np.zeros((existing_array.shape[0] + 2 * border_size, existing_array.shape[1] + 2 * border_size))

# Copy the existing array into the center of the new array
new_array[border_size:-border_size, border_size:-border_size] = existing_array

# Print the existing array and the new array with the border
print("Existing Array:")
print(existing_array)

print("\nNew Array with Border:")
print(new_array)

Existing Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

New Array with Border:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
# Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal
matrix = np.diag(1 + np.arange(4), k=-1)

# Print the matrix
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1

# Print the checkerboard matrix
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
array_shape = (6, 7, 8)
array = np.arange(np.prod(array_shape)).reshape(array_shape)

# Find the index of the 100th element
index_100th_element = np.unravel_index(99, array_shape)

# Print the result
print("Index (x, y, z) of the 100th element:", index_100th_element)

Index (x, y, z) of the 100th element: (1, 5, 3)


In [20]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
# Create a checkerboard 8x8 matrix using the tile function
checkerboard_matrix = np.tile([[0, 1], [1, 0]], (4, 4))

# Print the checkerboard matrix
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
random_matrix = np.random.rand(5, 5)

# Normalize the random matrix
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))

# Print the original and normalized matrices
print("Original Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.36227641 0.28820577 0.01993453 0.62157117 0.30986353]
 [0.56069733 0.94471185 0.74534702 0.25660871 0.05473308]
 [0.44687468 0.86309192 0.26808363 0.89384013 0.4661593 ]
 [0.8238042  0.01541244 0.46217634 0.74035996 0.87764039]
 [0.33735071 0.38378452 0.02169729 0.54281705 0.61437698]]

Normalized Matrix:
[[0.37325319 0.2935473  0.00486613 0.65227495 0.31685277]
 [0.58676987 1.         0.7854676  0.25954636 0.04231214]
 [0.46428765 0.91217047 0.27189428 0.94525799 0.48503944]
 [0.86989376 0.         0.48075345 0.78010113 0.92782578]
 [0.34643116 0.39639762 0.006763   0.56752926 0.64453344]]


In [22]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Create an array with the custom dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=rgba_dtype)

# Print the array with RGBA values
print(color_array)

[(255,   0, 0, 255) (  0, 255, 0, 128)]


In [23]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
array_1d = np.array([1, 5, 7, 4, 2, 9, 6, 3, 8])

# Negate elements between 3 and 8 in place
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1

# Print the modified array
print(array_1d)

[ 1 -5 -7 -4  2  9 -6  3  8]


In [24]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-01-03
Today: 2024-01-04
Tomorrow: 2024-01-05


In [25]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
start_date = datetime(2016, 7, 1)

# Calculate the number of days in July
days_in_july = 31

# Generate all the dates in July 2016
july_dates = [start_date + timedelta(days=i) for i in range(days_in_july)]

# Print the dates
for date in july_dates:
    print(date)

2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


In [26]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10  # Adjust the size or range as needed

# Method 1: Using astype(int)
integer_part_method1 = random_array.astype(int)

# Method 2: Using floor from numpy
integer_part_method2 = np.floor(random_array)

# Method 3: Using trunc from numpy
integer_part_method3 = np.trunc(random_array)

# Method 4: Using int() function
integer_part_method4 = np.array([int(x) for x in random_array])

# Print the results
print("Original Array:", random_array)
print("Method 1:", integer_part_method1)
print("Method 2:", integer_part_method2)
print("Method 3:", integer_part_method3)
print("Method 4:", integer_part_method4)


Original Array: [8.0469412  0.86698441 4.05210477 1.41722949 8.19517683]
Method 1: [8 0 4 1 8]
Method 2: [8. 0. 4. 1. 8.]
Method 3: [8. 0. 4. 1. 8.]
Method 4: [8 0 4 1 8]


In [27]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5, 5)) + np.arange(5)

# Print the matrix
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12)[1:-1]

# Print the vector
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

# Print the original and sorted vectors
print("Original Vector:", random_vector)
print("Sorted Vector:", sorted_vector)

Original Vector: [0.01675707 0.55675625 0.19838917 0.7109653  0.55128069 0.87280192
 0.59132251 0.8593891  0.86849806 0.37998067]
Sorted Vector: [0.01675707 0.19838917 0.37998067 0.55128069 0.55675625 0.59132251
 0.7109653  0.8593891  0.86849806 0.87280192]


In [30]:
#### 58. Subtract the mean of each row of a matrix (★★☆)
# Create a sample matrix (you can replace this with your own matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Subtract the mean of each row
result_matrix = matrix - np.mean(matrix, axis=1, keepdims=True)

# Print the original and resulting matrices
print("Original Matrix:")
print(matrix)
print("\nResulting Matrix after subtracting mean of each row:")
print(result_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Resulting Matrix after subtracting mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
